# Generated by Django 3.2.6 on 2021-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=50)),
                ('donarname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobilenumber', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('lastdonatedate', models.DateField()),
            ],
        ),
    ]
