# Generated by Django 3.2.6 on 2021-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminloginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eusername', models.CharField(max_length=200)),
                ('epassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=200)),
                ('eemail', models.CharField(max_length=200)),
                ('epassword', models.CharField(max_length=200)),
                ('emobile', models.BigIntegerField()),
            ],
        ),
    ]
